version: "3"

volumes:
  db_volume:

services:
  proxy:
    build: ./nginx
    container_name: proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"

  bot:
    build:
      context: ./
      dockerfile: Dockerfile.bot
    container_name: bot
    restart: always
    depends_on:
      - database
      - backend
      - checker
    volumes:
      - ./:/app
    env_file:
      - ./.env

  backend:
    build:
      context: ./
      dockerfile: Dockerfile.back
    container_name: backend
    restart: always
    depends_on:
      - database
      - proxy
    volumes:
      - ./:/app
    env_file:
      - ./.env


  checker:
    build:
      context: ./
      dockerfile: Dockerfile.check
    container_name: checker
    restart: always
    depends_on:
      - database
    volumes:
      - ./:/app
    env_file:
      - ./.env

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: database
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
