"""add_present

Revision ID: 357985b9d8e1
Revises: fe4120ce643d
Create Date: 2024-08-26 05:05:51.532079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '357985b9d8e1'
down_revision: Union[str, None] = 'fe4120ce643d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('present', sa.Boolean(), nullable=True), schema='users')
    op.alter_column('user', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               schema='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id',
               existing_type=sa.BIGINT(),
               server_default=sa.text("nextval('users.user_id_seq'::regclass)"),
               existing_nullable=False,
               schema='users')
    op.drop_column('user', 'present', schema='users')
    # ### end Alembic commands ###
